apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground
  namespace: argocd
spec:
  project: dev
  source:
    repoURL: https://github.com/Nakusu/owl-llepage-svolodin
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
