server_ip = "192.168.56.110"
worker_ip = "192.168.56.111"

token = "hibou"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine318"
  config.vm.box_version = "4.3.12"
  config.vm.synced_folder ".", "/vagrant" 
 
  config.vm.define "svolodinS" do |server|
    server.vm.hostname = "svolodinS"
    server.vm.network :private_network, ip: server_ip
    server.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
      v.memory = "2048"
      v.cpus = "2"
    end
    server.vm.provision "shell", path: "./scripts/server_setup.sh",
      args: [token, server_ip]
  end
    
  config.vm.define "svolodinSW" do |worker|
    worker.vm.hostname = "svolodinSW"
    worker.vm.network :private_network, ip: worker_ip 
    worker.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
      v.memory = "2048"
      v.cpus = "2"
    end
    worker.vm.provision "shell", path: "./scripts/worker_setup.sh",
      args: [token, server_ip, worker_ip]
  end
end
